### ISSUE TITLE
Use vendoring?

### ISSUE THREAD

**Issue by AurelienGasser** [Substra/substra-chaincode#25]
Currently, we have a `vendor/` directory, which indicates that we want to use vendored dependencies. However, **the project doesn't currently use vendored dependencies consistently**. 

In particular:

1. Some of the dependencies are missing from the `vendor/` directory
    - You can see it by typing `go build -mod=vendor`: this command is going to complain about missing dependencies
    - The fix would be to run `go mod vendor` and commit the updated vendored dependencies [1]
2. The README doesn't instruct users to use the `-mod=vendor` option. Without this option, the vendored dependencies are ignored [2]
3. The CI build doesn't use vendored dependencies (it doesn't use `-mod=vendor`)
4. The CI build doesn't check the integrity of dependencies (it doesn't call `go mod verify`) [3]
5. I'm not sure whether `hlf-k8s` uses vendored dependencies when instanciating the chaincode?

Hence my question:  **Do we want to use vendored dependencies?** 

If so, in order to be consistent, we should address the points above :)

[1] https://tip.golang.org/cmd/go/#hdr-Make_vendored_copy_of_dependencies

[2] https://tip.golang.org/cmd/go/#hdr-Modules_and_vendoring

[3] https://tip.golang.org/cmd/go/#hdr-Verify_dependencies_have_expected_content

**Comment by Kelvin-M** [comment]
@AurelienGasser : It looks like we don't use vendor, we may to remove it no ?

**Comment by thibaultrobert** [comment]
Back to the hyperledger 1, it was the only way to install the needed libraries since we didn't have the hand on the docker image. If you can now use modules (with internet or a proxy), the `go.mod` and `go.sum` files are enough. Or you can also fetch the dependencies when building the image you use for the chaincode. That depends on the new chaincode life cycle.

**Comment by thibaultrobert** [comment]
As to answer how this vendoring was done, it was indeed by running `go mod vendor` but to limit the size of the vendor it was the libraries that was already present from the chaincode image was removed by hand.

And for how it's used, a `vendor` file will be automatically used by go since 1.6 I think. But it's not the recommended way since go modules ensures the version of the dependencies now.

**Comment by Kelvin-M** [comment]
So we can remove it safely ? :)

**Comment by thibaultrobert** [comment]
Like I said, it depends on your chaincode lifecycle and its image building. Which I'm not certain I'm up to date with now...

**Comment by Kelvin-M** [comment]
Chaincode has now a docker image built with this dockerfile https://github.com/SubstraFoundation/substra-chaincode/blob/master/Dockerfile
It's the image which is used with the new lifecycle

**Comment by thibaultrobert** [comment]
Assuming the build process has access to internet (which is likely but it does not hurt to mention it), yes you can definitely remove this turd of vendor files. I'm going to validate your PR right now.

**Comment by Kelvin-M** [comment]
Yes, it has internet as substra-chaincode is on docker hub :D
